import type { Transaction, Wallet, Budget, Category } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [];

export const INITIAL_WALLETS: Wallet[] = [];

export const INITIAL_BUDGETS: Budget[] = [];

export const CATEGORIES: Category[] = [
  { name: 'Salary', icon: '💼', type: 'income', color: 'bg-emerald-100 text-emerald-700' },
  { name: 'Freelance', icon: '💻', type: 'income', color: 'bg-teal-100 text-teal-700' },
  { name: 'Investments', icon: '📈', type: 'income', color: 'bg-blue-100 text-blue-700' },
  { name: 'Groceries', icon: '🛒', type: 'expense', color: 'bg-amber-100 text-amber-700' },
  { name: 'Dining Out', icon: '🍔', type: 'expense', color: 'bg-orange-100 text-orange-700' },
  { name: 'Shopping', icon: '🛍️', type: 'expense', color: 'bg-purple-100 text-purple-700' },
  { name: 'Fuel', icon: '⛽', type: 'expense', color: 'bg-rose-100 text-rose-700' },
  { name: 'Utilities', icon: '⚡', type: 'expense', color: 'bg-yellow-100 text-yellow-700' },
];

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    profile: "Profile",
    activity: "Activity",
    ai: "AI",
    stats: "Stats",
    wallets: "Wallets",
    add: "Add",
    search: "Search here...",
    overview: "Overview",
    income: "Income",
    expense: "Expense",
    recent: "Recent Transactions",
    viewAll: "View All",
    limits: "Spending Limits",
    available: "Available Funds",
    history: "Transaction History",
    manage: "Manage",
    save: "Save Transaction",
    note: "Note / Description",
    amount: "Amount",
    category: "Category",
    wallet: "Wallet",
    source: "Income Source / Person",
    selectLang: "Select Language"
  },
  ur: {
    dashboard: "ڈیش بورڈ",
    profile: "پروفائل",
    activity: "سرگرمی",
    ai: "مصنوعی ذہانت",
    stats: "اعداد و شمار",
    wallets: "والٹس",
    add: "جمع کریں",
    search: "یہاں تلاش کریں...",
    overview: "جائزہ",
    income: "آمدنی",
    expense: "خرچہ",
    recent: "حالیہ لین دین",
    viewAll: "سب دیکھیں",
    limits: "اخراجات کی حد",
    available: "دستیاب فنڈز",
    history: "لین دین کی تاریخ",
    manage: "انتظام کریں",
    save: "لین دین محفوظ کریں",
    note: "نوٹ / تفصیل",
    amount: "رقم",
    category: "زمرہ",
    wallet: "والٹ",
    source: "آمدنی کا ذریعہ / شخص",
    selectLang: "زبان منتخب کریں"
  },
  ar: {
    dashboard: "لوحة القيادة",
    profile: "الملف الشخصي",
    activity: "النشاط",
    ai: "الذكاء الاصطناعي",
    stats: "الإحصائيات",
    wallets: "المحافظ",
    add: "إضافة",
    search: "ابحث هنا...",
    overview: "نظرة عامة",
    income: "دخل",
    expense: "مصروف",
    recent: "المعاملات الأخيرة",
    viewAll: "عرض الكل",
    limits: "حدود الإنفاق",
    available: "الأموال المتاحة",
    history: "سجل المعاملات",
    manage: "إدارة",
    save: "حفظ المعاملة",
    note: "ملاحظة / وصف",
    amount: "المبلغ",
    category: "فئة",
    wallet: "محفظة",
    source: "مصدر الدخل / الشخص",
    selectLang: "اختر اللغة"
  },
  es: {
    dashboard: "Tablero",
    profile: "Perfil",
    activity: "Actividad",
    ai: "IA",
    stats: "Estadísticas",
    wallets: "Billeteras",
    add: "Añadir",
    search: "Busca aquí...",
    overview: "Visión general",
    income: "Ingresos",
    expense: "Gastos",
    recent: "Transacciones recientes",
    viewAll: "Ver todo",
    limits: "Límites de gasto",
    available: "Fondos disponibles",
    history: "Historial de transacciones",
    manage: "Gestionar",
    save: "Guardar transacción",
    note: "Nota / Descripción",
    amount: "Monto",
    category: "Categoría",
    wallet: "Billetera",
    source: "Fuente / Persona",
    selectLang: "Seleccionar idioma"
  },
  fr: {
    dashboard: "Tableau de bord",
    profile: "Profil",
    activity: "Activité",
    ai: "IA",
    stats: "Statistiques",
    wallets: "Portefeuilles",
    add: "Ajouter",
    search: "Cherchez ici...",
    overview: "Aperçu",
    income: "Revenu",
    expense: "Dépense",
    recent: "Transactions récentes",
    viewAll: "Voir tout",
    limits: "Limites de dépenses",
    available: "Fonds disponibles",
    history: "Historique des transactions",
    manage: "Gérer",
    save: "Enregistrer la transaction",
    note: "Note / Description",
    amount: "Montant",
    category: "Catégorie",
    wallet: "Portefeuille",
    source: "Source de revenu / Personne",
    selectLang: "Choisir la langue"
  }
};
